# Generated by Django 3.2.9 on 2021-11-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_surat', models.DateField()),
                ('nomor_surat', models.CharField(max_length=50)),
                ('jenis_surat', models.CharField(max_length=50)),
                ('tujuan', models.CharField(max_length=50)),
                ('perihal', models.CharField(max_length=50)),
                ('mengetahui', models.CharField(max_length=50)),
                ('arsip', models.CharField(max_length=50)),
                ('ket', models.CharField(max_length=50)),
            ],
        ),
    ]
