# Generated by Django 3.2.9 on 2021-11-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websurat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surat',
            name='arsip',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='jenis_surat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='ket',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='mengetahui',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='nomor_surat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='perihal',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='tujuan',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
