# Generated by Django 3.2.9 on 2021-11-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websurat', '0002_auto_20211124_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surat',
            name='tgl_surat',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
