# Generated by Django 3.2.9 on 2021-11-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websurat', '0003_alter_surat_tgl_surat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surat',
            name='arsip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='jenis_surat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='ket',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='mengetahui',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='perihal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='tgl_surat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='tujuan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
